# Generated by Django 5.0.4 on 2024-04-15 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('dated', models.DateField(default=datetime.datetime(2024, 4, 15, 11, 21, 47, 850802, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
