# Generated by Django 5.0.4 on 2024-04-17 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dated',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 11, 26, 24, 664228, tzinfo=datetime.timezone.utc)),
        ),
    ]
