# Generated by Django 5.0.4 on 2024-04-30 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author_alter_post_dated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='dated',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 10, 4, 4, 435941, tzinfo=datetime.timezone.utc)),
        ),
    ]
