# Generated by Django 5.0.4 on 2024-04-30 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_featured_alter_post_dated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='dated',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 10, 18, 1, 823979, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
