# Generated by Django 5.0.4 on 2024-04-30 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_alter_post_dated_post_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dated',
            field=models.DateField(default=datetime.datetime(2024, 4, 30, 10, 20, 59, 452791, tzinfo=datetime.timezone.utc)),
        ),
    ]
